version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: bem6u/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/kittygram_backend_static/
      - media:/app/media/
    restart: on-failure

  frontend:
    env_file: .env
    image: bem6u/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/
    restart: no
  gateway:
    image: bem6u/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/app/media/
    restart: always
