version: '3'

volumes:
  pg_data_kity:
  static_kitty:
  media_kitty:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kity:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static_kitty:/backend_static
      - media_kitty:/app/media
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_kitty:/static


  gateway:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static_kitty:/staticfiles/
      - media_kitty:/app/media/
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend



